#!/bin/bash
yum update -y
yum install httpd -y
service httpd start
chkconfig httpd on
cd /var/www/html
echo "<html><h1>Welcome! Apache Web Server Installation Succeeded. Therefore, you are able to see this screen</h1></html>" > index.html
